SELECT *
FROM GDP_inference;

SELECT *
FROM GDP_inference
WHERE gdp IS NOT NULL;


SELECT MIN(EXTRACT(YEAR FROM date)) AS first_complete_year
FROM GDP_inference
WHERE
    gdp IS NOT NULL
    AND PRS85006091 IS NOT NULL
    AND UNRATE IS NOT NULL
    AND DEXUSEU IS NOT NULL
    AND DFF IS NOT NULL
    AND CORESTICKM159SFRBATL IS NOT NULL
    AND gdp IS NOT NULL
    AND POPTHM IS NOT NULL;


ALTER TABLE GDP_inference
DROP COLUMN DEXUSEU ;

CREATE TABLE GDP_inference_clean AS
SELECT *
FROM GDP_inference
WHERE date >= '1999-01-01'
AND gdp IS NOT  NULL;

SHOW TABLES;